version: '3.8'

services:
  web:
    image: house-price-flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NAME=World
    restart: unless-stopped