name: CI/CD for Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flask
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest
  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with :
        contect: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/house-price-flask-app:latest
    
    - name: Run Docker container
      run: docker run -d -p 5000:5000 house-price-flask-app


    # - name: Push Docker image to DockerHub (Optional)
    #   run: |
    #     echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    #     docker tag house-price-flask-app:latest yourusername/house-price-flask-app:latest
    #     docker push yourusername/house-price-flask-app:latest
